apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
    - image: keptnsandbox/artillery-service # Todo: Replace this with your image name
      docker:
        dockerfile: Dockerfile
        buildArgs:
          debugBuild: true
deploy:
  kubectl:
    manifests:
      - deploy/service.yaml
