---
# Deployment of artillery-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: artillery-service
  namespace: keptn
spec:
  selector:
    matchLabels:
      run: artillery-service
  replicas: 1
  template:
    metadata:
      labels:
        run: artillery-service
        app.kubernetes.io/name: artillery-service
        app.kubernetes.io/version: 0.3.1
    spec:
      containers:
        - name: artillery-service
          image: keptnsandbox/artillery-service:0.3.1
          ports:
            - containerPort: 8080
          env:
            - name: CONFIGURATION_SERVICE
              value: 'http://configuration-service:8080'
        - name: distributor
          image: keptn/distributor:0.8.4
          livenessProbe:
            httpGet:
              path: /health
              port: 10999
            initialDelaySeconds: 5
            periodSeconds: 5
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "16Mi"
              cpu: "25m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          env:
            - name: PUBSUB_URL
              value: 'nats://keptn-nats-cluster'
            - name: PUBSUB_TOPIC
              value: 'sh.keptn.event.test.triggered'
            - name: PUBSUB_RECIPIENT
              value: '127.0.0.1'
            - name: VERSION
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: 'metadata.labels[''app.kubernetes.io/version'']'
            - name: K8S_DEPLOYMENT_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: 'metadata.labels[''app.kubernetes.io/name'']'
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
      serviceAccountName: keptn-default
---
# Expose artillery-service via Port 8080 within the cluster
apiVersion: v1
kind: Service
metadata:
  name: artillery-service
  namespace: keptn
  labels:
    run: artillery-service
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    run: artillery-service

