---
# Deployment of artillery-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: artillery-service
  namespace: keptn
spec:
  selector:
    matchLabels:
      run: artillery-service
  replicas: 1
  template:
    metadata:
      labels:
        run: artillery-service
    spec:
      containers:
        - name: artillery-service
          image: keptnsandbox/artillery-service:0.1.0
          ports:
            - containerPort: 8080
          env:
            - name: CONFIGURATION_SERVICE
              value: 'http://configuration-service:8080'
        - name: distributor
          image: keptn/distributor:0.8.1
          livenessProbe:
            httpGet:
              path: /health
              port: 10999
            initialDelaySeconds: 5
            periodSeconds: 5
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "16Mi"
              cpu: "25m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          env:
            - name: PUBSUB_URL
              value: 'nats://keptn-nats-cluster'
            - name: PUBSUB_TOPIC
              value: 'sh.keptn.event.test.triggered'
            - name: PUBSUB_RECIPIENT
              value: '127.0.0.1'
      serviceAccountName: keptn-default
---
# Expose artillery-service via Port 8080 within the cluster
apiVersion: v1
kind: Service
metadata:
  name: artillery-service
  namespace: keptn
  labels:
    run: artillery-service
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    run: artillery-service

